fd_offer_index:
    path:    /Offer/Index
    defaults:
       _controller:    FDOfferBundle:Offer:index

fd_offer_get:
    path:    /Offer/Get1N2
    defaults:
        _controller:    FDOfferBundle:Offer:get1N2