fd_team_index:
    path:    /Team/Index
    defaults:
       _controller:    FDTeamBundle:Team:index

fd_team_get:
    path:    /Team/Get
    defaults:
        _controller:    FDTeamBundle:Team:get

fd_team_result:
    path:    /Team/Result
    defaults:
        _controller:    FDTeamBundle:Team:result

fd_team_rank:
    path:    /Team/Rank
    defaults:
        _controller:    FDTeamBundle:Team:Rank