fd_bet:
    resource: "@FDBetBundle/Resources/config/routing.yml"
    prefix:   /

fd_main:
    resource: "@FDMainBundle/Resources/config/routing.yml"
    prefix:   /

fd_team:
    resource: "@FDTeamBundle/Resources/config/routing.yml"
    prefix:   /

fd_result:
    resource: "@FDResultBundle/Resources/config/routing.yml"
    prefix:   /

fd_offer:
    resource: "@FDOfferBundle/Resources/config/routing.yml"
    prefix:   /
